#spring:
#  datasource:
#     username: root 
#      password: Sak@cog$12
#      url: jdbc:mysql://localhost:3306/registrationdb
#      driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#   show-sql: true
#   hibernate:
#      ddl-auto: update
#   properties.hibernate.dilect: org.hibernate.dialect.MySQL5Dialect     